### ISSUE TITLE
noise.snoise3 doesn't take a seed argument

### ISSUE THREAD

**Issue by magnaou** [PMEAL/porespy#200] opened 2019-10-02 21:17 UTC
This makes using "ps.generators.generate_noise(args)" reproducible and doesn't allow us to generate different media of the same size.

**Comment by jgostick** [comment] 2019-10-04 03:26
The problem is that noise is an external package.  I don't know if it even uses the numpy random number generator.

**Comment by jgostick** [comment] 2019-10-14 15:45
Also see issue #81

**Comment by jgostick** [comment] 2020-04-08 02:26
This is now fixed with PR #223, since you can set the numpy random number generator before calling the function.

**Closed by jgostick** 2020-04-08 02:26 UTC
