### ISSUE TITLE
_parse_pad_width fails when given list of lists

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#572] opened 2021-08-10 16:30 UTC
Try with ```pw = [[0, 0], [0, 0], [3, 3]]```.

**Comment by jgostick** [comment] 2022-03-18 20:18
This works for me.  I also had the feeling that this function wasn't working but it now is (I closed a related issue today).  The above ``pw`` works fine and produces:  [[0, 0], [0, 0], [3, 3]], which is the input since you specified all the axes explicitly.  Before I close this, can try to reproduce the error?

**Comment by ma-sadeghi** [comment] 2022-03-27 11:38
Passing a simple list works:

```python
import porespy as ps

pw = [0, 0, 3]

ps.networks._snow2._parse_pad_width(pw, shape=[100, 100, 100])
Out[16]: 
array([[0, 0],
       [0, 0],
       [3, 3]])
```

whereas passing a list of list produces `dtype=object`, which is not liked by porespy.

```python
import porespy as ps

pw = [[0, 0], [0, 0], [3, 3]]

ps.networks._snow2._parse_pad_width(pw, shape=[100, 100, 100])
Out[14]: 
array([[0, 0],
       [0, 0],
       [3, 3]], dtype=object)
```

**Closed as completed** 2023-03-15 21:18 UTC
Labels: bug, high priority, easy
